# .____   .                                   .            .   .____
# /       |     ___  , _ , _     ___  , __   _/_     ___   |   /        ___    __.  , __     __.  , _ , _   ,    .
# |__.    |   .'   ` |' `|' `. .'   ` |'  `.  |     /   `  |   |__.   .'   ` .'   \ |'  `. .'   \ |' `|' `. |    `
# |       |   |----' |   |   | |----' |    |  |    |    |  |   |      |      |    | |    | |    | |   |   | |    |
# /----/ /\__ `.___, /   '   / `.___, /    |  \__/ `.__/| /\__ /----/  `._.'  `._.' /    |  `._.' /   '   /  `---|
#                                                                                                            \___/
#
# This is plugin.yml, a hidden file which *should not* be configured by anyone other than developers of the resource.

# General information:
name: ElementalEconomy
version: ${project.version}
description: ${project.description}
author: lokka30

# Dependencies:
# Note: Vault is only required for plugins not direclty using the ElemEcon API.
softdepend: [ 'Vault' ]

# Other information for Bukkit:
main: me.lokka30.elementaleconomy.ElementalEconomy
# 1.13 is specified for 1.13+ compatibilty, as for example, 1.16 would not allow
# 1.13-1.15 servers to run ElemEcon. The plugin should be compiled with the
# latest version of Spigot however.
api-version: '1.13'

# These are the commands that ElementalEconomy registers.
commands:

  # /balance
  balance:
    description: View a player's balance.
    usage: /<command> [player] [currency]
    aliases: [ bal, money ]

  # /baltop
  baltop:
    description: View the leaderboard of top balances.
    usage: /<command> [currency] [page]
    aliases: [ balancetop, topbal, topbalances, topbalance ]

  # /economy
  economy:
    description: Manage accounts' balances.
    usage: /<command> <give|add/take|remove/set/reset> <...>
    aliases: [ eco, econ ]

  # /elementaleconomy
  elementaleconomy:
    description: View information about ElementalEconomy or manage parts of it, such as creating backups or reloading the plugin.
    usage: /<command> <info/reload/backup/compatibility>
    aliases: [ elemecon, elementalecon, elemeconomy, eeconomy ]

  # /pay
  pay:
    description: Transfer money from your account to another's.
    usage: /<command> <player> <amount> [currency]