# .____   .                                   .            .   .____
# /       |     ___  , _ , _     ___  , __   _/_     ___   |   /        ___    __.  , __     __.  , _ , _   ,    .
# |__.    |   .'   ` |' `|' `. .'   ` |'  `.  |     /   `  |   |__.   .'   ` .'   \ |'  `. .'   \ |' `|' `. |    `
# |       |   |----' |   |   | |----' |    |  |    |    |  |   |      |      |    | |    | |    | |   |   | |    |
# /----/ /\__ `.___, /   '   / `.___, /    |  \__/ `.__/| /\__ /----/  `._.'  `._.' /    |  `._.' /   '   /  `---|
#                                                                                                            \___/
#
# Welcome to the ElementalEconomy settings.yml file. This is the file to configure settings not otherwise covered
# by 'currencies.yml' and 'messages.yml', such as toggling the update checker and debug functionality.
#
# We highly recommend you send your edits through a YAML Parser. Beginner server owners are likely to make mistakes
# whilst editing YAML files such as using the incorrect indentation, formatting, values, apostrophes, and so on.
#
# Happy configuring!

# Configure the storage system ElementalEconomy uses to store accounts and their balances.
storage:

  # How should ElementalEconomy store balances?
  #
  # README if you plan on changing this:
  # - Balances do not transfer from your previous storage solution.
  # - Balances do not wipe from your previous storage solution.
  #   If you switch to a storage method previously used then
  #   the balances stored there will be used.
  # - If using MySQL, ensure you have the database details filled
  #   out. See 'mysql-settings' below.
  #
  # Available storage methods:
  # - SQLite (highly recommended for most servers, and the default choice)
  #   > Local database stored in the ElementalEconomy folder.
  #   + Fastest, and far faster than YAML.
  #   - Cannot synchronise with other servers.
  #   - Difficult to manually edit data.
  #   + No configuration.
  #
  # - MySQL (required for balance synchronisation, if you need it)
  #   > Database stored in your MySQL server.
  #   + Fast.
  #   + Can synchronise with other servers.
  #   - Difficult to manually edit data.
  #   - Requires configuration below in mysql-settings.
  #
  # - YAML (great for small communities & if you need full control over your data)
  #   > Configuration-like file stored in the ElementalEconomy folder.
  #   - Quite fast, although slower than SQLite, although
  #     only an issue when lots of users are stored.
  #   - Cannot synchronise with other servers.
  #   + Easy to manually edit data.
  #   + No configuration.
  #
  method: SQLite


  # You must change these settings if you are using MySQL. If you are not using MySQL then changing these
  # settings will make no effect. Triple-check that you have set the correct values below BEFORE starting
  # the plugin up.
  mysql-settings:
    username: 'user123'
    password: 'pass123'
    database: 'minecraft'
    host: 'localhost:3306'


# These settings control the 'baltop' system - a command that shows the top balances for each currency
# you have configured.
baltop:

  # Should the system be enabled?
  # Feel free to disable the baltop system if your server never uses it.
  # Very small resource savings, but hey, you have the choice ;)
  # By default, this is enabled (true).
  enabled: true

  # How frequently, in minutes, should the baltop system 'refresh' itself?
  # Lower values = may consume an unnecessary amount of CPU / load on the storage system
  # Higher values = players will have to wait longer to see the latest balances on baltop
  # Recommended values: 7 to 20 minutes. By default, this is 10 minutes (10).
  auto-cache-task-period: 10

  # How many users should be displayed on each baltop page? By default, this is 10 pages (10).
  users-per-page: 10


# A quiet async update checker that does its job once when the plugin starts up and then leaves you alone. This
# feature only works on 1.11+ servers, please disable it if your server is running a version older than 1.11.
# By default, this is enabled (true).
check-for-updates: true


# ** It is not recommended to suppress ElementalEconomy warnings. You should try fix them instead! **
# If ElementalEconomy is annoying you with warnings, then there is a high chance you can disable them here.
suppressed-warnings:

  # If 'false', ElementalEconomy will complain when other plugins access deprecated Vault methods.
  # Please inform the plugin developer(s) at fault to make the switch to non-reprecated Vault methods.
  DEPRECATED_VAULT_METHOD_CALL: false

  # If 'false', ElementalEconomy will complain when other plugins access Vault methods that ElementalEconomy does not support,
  #
  # If you are receiving errors regarding banks:
  #  - The plugin trying to access Vault's bank methods is disregarding if the economy provider (i.e. ElementalEconomy) has bank support.
  #  - Please inform the plugin developer(s) of the plugin that is causing this warning with this information.
  #
  # If you are receiving errors regarding createPlayerAccount:
  #  - You have a plugin installed that is trying to tell ElementalEconomy to make a new account for a player, but
  #    ElementalEconomy does this automatically anyways. Vault's documentation tells developers that the methods
  #    are implementation-specific anyways.
  #  - Please inform the developer(s) of the plugin at fault to add an ability to toggle this behaviour.
  UNSUPPORTED_VAULT_METHOD_CALL: false


# *** This is for developers to use, server owners should ignore this. ***
# Debugging prints a *ton* of spam to the console which is useful for developers to get information towards fixing bugs.
# Note for developers: Add the debug message type to this array for it to be logged (in UPPERCASE). Ask lokka30 if unsure.
debug: [ ]


# Do not touch this unless you know what you're doing!
file-version: 1